#!/bin/bash

# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2020 KBEmbedded

# Convert a monochrome BMP file to an init that is suitable for use
# in a header file.
#
# Icons are only 34x34, but requires a 40x34 source so it is byte aligned
#
# Usage:
#   icon_bmp_to_struct_init.sh <icon.bmp>

if [ $# -ne 1 ]; then
  echo "Usage:"
  echo "  ${0} <icon.bmp>"
  echo ""
  exit 1
fi

if [ ! -x "$(command -v convert)" ]; then
  echo "Error: convert is not available (is Imagemagick installed?)"
  exit 1
fi

FILENAME=$(basename -- "${1}")
FILENAME="${FILENAME%.*}"

convert "${1}" -monochrome MONO:"${FILENAME}".bin

# Build a .h and populate it with default struct/members for app icon
rm "${FILENAME}".h 2>/dev/null
echo "// Automatically generated by scripts/$(basename -- "${0}")" >> "${FILENAME}".h
echo "const dataflash_icon_no_icon1 app_icon = {" >> "${FILENAME}".h

# See src/include/dflash_app.h for information on these values
echo -e "\\t0xAD," >> "${FILENAME}".h	# icon0 size
echo -e "\\t0x8," >> "${FILENAME}".h	# icon0 start
echo -e "\\t0x0," >> "${FILENAME}".h	# icon1 size (unused)
echo -e "\\t0x0," >> "${FILENAME}".h	# icon1 start (unused)
echo -e "\\t0x22," >> "${FILENAME}".h	# icon0 width (should be 34 px)
echo -e "\\t0x22," >> "${FILENAME}".h	# icon0 height (should be 34 px)
echo -e "\\t{" >> "${FILENAME}".h

# Now need to write the 40x34 px binary array here in 8-bit bytes
hexdump -v  -e'"\t{ "' -e' 4/1 "0x%02X, "  1/1 " 0x%02X },\n"' "${FILENAME}".bin >> "${FILENAME}".h
echo -e "\\t}" >> "${FILENAME}".h
echo -e "};" >> "${FILENAME}".h

rm "${FILENAME}".bin 2>/dev/null
