/* All of these strings are indexed CFp15 */

/* Much of this was output/formatted from tools/misc/string_index
 * See that source for more info. */

/* String literals based on 3.03 firmware. May be different in other FW
 * versions
 */

/* The '+' string doesn't appear in the string list in CFp15 and might be some
 * special case? */

/* Handful of "app" defines to make things easier to track */
#define STR_IDX_APP00	0x8000
#define STR_IDX_APP01	0x8001
#define STR_IDX_APP02	0x8002
#define STR_IDX_APP03	0x8003
#define STR_IDX_APP04	0x8004
#define STR_IDX_APP05	0x8005
#define STR_IDX_APP06	0x8006
#define STR_IDX_APP07	0x8007
#define STR_IDX_APP08	0x8008
#define STR_IDX_APP09	0x8009
#define STR_IDX_APP10	0x800A
#define STR_IDX_APP11	0x800B
#define STR_IDX_APP12	0x800C
#define STR_IDX_APP13	0x800D
#define STR_IDX_APP14	0x800E
#define STR_IDX_APP15	0x800F

#define STR_IDX_PLUS	0x0000  // '+'
#define STR_IDX_CANCEL	0x0001	// 'Cancel'
#define STR_IDX_YES	0x0002	// 'Yes'
#define STR_IDX_NO	0x0003	// 'No'
#define STR_IDX_READ	0x0004	// 'Read'
#define STR_IDX_DEL	0x0005	// 'Delete'
#define STR_IDX_NEW	0x0006	// 'New'
#define STR_IDX_CHECK	0x0007	// 'Check'
#define STR_IDX_SEARCH	0x0008	// 'Search'
#define STR_IDX_MAIN	0x0009	// 'Main Menu\'
#define STR_IDX_REPLY	0x000A	// 'Reply'
#define STR_IDX_FWD	0x000B	// 'Forward'
#define STR_IDX_PRINT	0x000C	// 'Print'
#define STR_IDX_INBOX	0x000D	// 'Back to In Box'
#define STR_IDX_ADDR	0x000E	// 'Address Book'
#define STR_IDX_SEND	0x000F	// 'Send Now'
#define STR_IDX_SAVEOB	0x0010	// '&Save In Out Box'
#define STR_IDX_DETAIL	0x0011	// 'Detail'
#define STR_IDX_MOVE	0x0012	// 'Move'
#define STR_IDX_ADDCALL	0x0013	// 'Add Caller'
#define STR_IDX_CLOCK	0x0014	// 'Clock'
#define STR_IDX_MEM	0x0015	// 'Memory'
#define STR_IDX_FROM	0x0016	// 'From'
#define STR_IDX_DATE	0x0017	// 'Date'
#define STR_IDX_SUBJ	0x0018	// 'Subject'
#define STR_IDX_11MSG	0x0019	// 'You have 11 new messages!'
#define STR_IDX_LOWMEM	0x001A	// 'You have only 15% free memory. Do you want to optimize it ?'
#define STR_IDX_OPTCOM	0x001B	// 'Optimization is complete!	'
#define STR_IDX_CHECKAT	0x001C	// 'Check messages at '
#define STR_IDX_EVERYDA	0x001D	// 'every day'
#define STR_IDX_SAVESER	0x001E	// 'Save message copy on Server '
#define STR_IDX_MAXDL	0x001F	// 'Maximum size of mail to download '
#define STR_IDX_K	0x0020	// 'K [1 - 8]'
#define STR_IDX_AUTOPDN	0x0021	// 'Auto power down in '
#define STR_IDX_MINUTES	0x0022	// 'minutes'
#define STR_IDX_MEMCOL	0x0023	// 'Memory : '
#define STR_IDX_BATCOL	0x0024	// 'Battery : '
#define STR_IDX_STDBY	0x0025	// 'Please standby... Performing maintenance.'
#define STR_IDX_ON	0x0026	// 'On'
#define STR_IDX_OFF	0x0027	// 'Off'
#define STR_IDX_DAY	0x0028	// 'Day'
#define STR_IDX_WEEK	0x0029	// 'Week'
#define STR_IDX_MONTH	0x002A	// 'Month'
#define STR_IDX_PERSONA	0x002B	// 'Personal'
#define STR_IDX_BUSINES	0x002C	// 'Business'
#define STR_IDX_TOFAX	0x002D	// 'To &Fax'
#define STR_IDX_DELACCT	0x002E	// 'WARNING! Once deleted, you will no longer be able to send or receive e-mail through this account. Delete account?'
#define STR_IDX_EDIT	0x002F	// 'Edit'
#define STR_IDX_NAME	0x0030	// 'Name'
#define STR_IDX_EMADDR	0x0031	// 'E-Mail Address'
#define STR_IDX_FAX	0x0032	// 'Fax'
#define STR_IDX_PRINTIN	0x0033	// 'Printing...'
#define STR_IDX_SENDALL	0x0034	// 'Send All'
#define STR_IDX_TO	0x0035	// 'To'
#define STR_IDX_BACK	0x0036	// 'Back'

#define STR_IDX_NEXT	0x0198	// 'Next>'
#define STR_IDX_PREV	0x0199	// '<Previous'

#if 0
#define STR_IDX_	0x0037	// 'Send To'
#define STR_IDX_	0x0038	// 'Show Detail'
#define STR_IDX_	0x0039	// 'Create New'
#define STR_IDX_	0x003A	// 'Finish'
#define STR_IDX_	0x003B	// 'To:'
#define STR_IDX_	0x003C	// 'Date:'
#define STR_IDX_	0x003D	// 'Subject:'
#define STR_IDX_	0x003E	// 'Please enter an e-mail$address in the "To:" field.'
#define STR_IDX_	0x003F	// 'Sending E-Mail message...'
#define STR_IDX_	0x0040	// 'What do you want to$do with this message ?'
#define STR_IDX_	0x0041	// 'Save as a Dra&ft'
#define STR_IDX_	0x0042	// 'Sending E-Mail'
#define STR_IDX_	0x0043	// 'Disconnecting'
#define STR_IDX_	0x0044	// 'Dialing...'
#define STR_IDX_	0x0045	// 'How do you want to $ send this message ?'
#define STR_IDX_	0x0046	// 'To &E-Mail'
#define STR_IDX_	0x0047	// '&Discard'
#define STR_IDX_	0x0048	// 'How do you want to $ print this message ?'
#define STR_IDX_	0x0049	// '&E-Mail Format'
#define STR_IDX_	0x004A	// '&Letter Format'
#define STR_IDX_	0x004B	// 'There is a printing problem.$ Please check the printer cable$ and be sure the power is on.'
#define STR_IDX_	0x004C	// 'From:'
#define STR_IDX_	0x004D	// 'OK'
#define STR_IDX_	0x004E	// 'ISP Account: '
#define STR_IDX_	0x004F	// 'ISP Password: '
#define STR_IDX_	0x0050	// 'Dial-Up No: '
#define STR_IDX_	0x0051	// 'Alt Dial-Up No: '
#define STR_IDX_	0x0052	// 'POP3 Account: '
#define STR_IDX_	0x0053	// 'E-mail Password: '
#define STR_IDX_	0x0054	// 'POP3 Server: '
#define STR_IDX_	0x0055	// 'SMTP Server: '
#define STR_IDX_	0x0056	// 'Primary DNS: '
#define STR_IDX_	0x0057	// 'Secondary DNS: '
#define STR_IDX_	0x0058	// 'You have 5 active mailboxes.$Additional accounts can not be added.'
#define STR_IDX_	0x0059	// 'New Account'
#define STR_IDX_	0x005A	// 'Select Current User'
#define STR_IDX_	0x005B	// 'Options'
#define STR_IDX_	0x005C	// 'Please select an active user'
#define STR_IDX_	0x005D	// 'Save'
#define STR_IDX_	0x005E	// 'Automatically'
#define STR_IDX_	0x005F	// 'Now'
#define STR_IDX_	0x0060	// 'Perform Memory maintenance now?'
#define STR_IDX_	0x0061	// 'User Name: '
#define STR_IDX_	0x0062	// 'Optimize'
#define STR_IDX_	0x0063	// 'select'
#define STR_IDX_	0x0064	// 'Account'
#define STR_IDX_	0x0065	// 'Current user'
#define STR_IDX_	0x0066	// 'Sent Mail'
#define STR_IDX_	0x0067	// 'Enter'
#define STR_IDX_	0x0068	// 'Do you want to rewrite this mail?'
#define STR_IDX_	0x0069	// 'Dialing...$Logging on...$Sending E-Mail$Disconnecting'
#define STR_IDX_	0x006A	// 'All mail sent.'
#define STR_IDX_	0x006B	// 'There is no mail in Inbox !'
#define STR_IDX_	0x006C	// 'There is no mail in Outbox !'
#define STR_IDX_	0x006D	// 'Checking E-Mail message...'
#define STR_IDX_	0x006E	// 'Dialing...$Logging on...$Checking E-Mail$Disconnecting'
#define STR_IDX_	0x006F	// 'Contain:'
#define STR_IDX_	0x0070	// 'by Author'
#define STR_IDX_	0x0071	// 'by Date'
#define STR_IDX_	0x0072	// 'by Subject'
#define STR_IDX_	0x0073	// 'by Unread'
#define STR_IDX_	0x0074	// 'Start Search'
#define STR_IDX_	0x0075	// 'New Year's Day'
#define STR_IDX_	0x0076	// 'Washington's Birthday'
#define STR_IDX_	0x0077	// 'Prince Kuhio Day'
#define STR_IDX_	0x0078	// 'International Labor Day'
#define STR_IDX_	0x0079	// 'Memorial Day'
#define STR_IDX_	0x007A	// 'Kamehameha Day'
#define STR_IDX_	0x007B	// 'Independence Day'
#define STR_IDX_	0x007C	// 'Admission Day'
#define STR_IDX_	0x007D	// 'Labor Day'
#define STR_IDX_	0x007E	// 'Columbus Day'
#define STR_IDX_	0x007F	// 'Aloha Week'
#define STR_IDX_	0x0080	// 'Veterans Day'
#define STR_IDX_	0x0081	// 'Thanksgiving Day'
#define STR_IDX_	0x0082	// 'Christmas'
#define STR_IDX_	0x0083	// 'No space'
#define STR_IDX_	0x0084	// 'Calendar'
#define STR_IDX_	0x0085	// 'Daily Events'
#define STR_IDX_	0x0086	// 'Search'
#define STR_IDX_	0x0087	// 'Today'
#define STR_IDX_	0x0088	// 'Alarm'
#define STR_IDX_	0x0089	// 'Please input the date:'
#define STR_IDX_	0x008A	// 'Calendar/Search'
#define STR_IDX_	0x008B	// 'Modify'
#define STR_IDX_	0x008C	// 'New Diary'
#define STR_IDX_	0x008D	// 'Calendar/Diary'
#define STR_IDX_	0x008E	// 'Invalid Day'
#define STR_IDX_	0x008F	// 'No Diary'
#define STR_IDX_	0x0090	// 'Sending'
#define STR_IDX_	0x0091	// 'Group Name: '
#define STR_IDX_	0x0092	// 'Input Group Name: '
#define STR_IDX_	0x0093	// 'Others: '
#define STR_IDX_	0x0094	// 'Pager: '
#define STR_IDX_	0x0095	// 'Fax Number: '
#define STR_IDX_	0x0096	// 'Mobile Phone: '
#define STR_IDX_	0x0097	// 'Office Phone: '
#define STR_IDX_	0x0098	// 'Home Phone: '
#define STR_IDX_	0x0099	// 'E-Mail Address: '
#define STR_IDX_	0x009A	// 'Last Name: '
#define STR_IDX_	0x009B	// 'First Name: '
#define STR_IDX_	0x009C	// '&Groups'
#define STR_IDX_	0x009D	// 'In&dividuals'
#define STR_IDX_	0x009E	// 'Edit Entry'
#define STR_IDX_	0x009F	// 'Add'
#define STR_IDX_	0x00A0	// 'New Group'
#define STR_IDX_	0x00A1	// 'Save'
#define STR_IDX_	0x00A2	// 'New Entry'
#define STR_IDX_	0x00A3	// 'Print'
#define STR_IDX_	0x00A4	// 'Entries'
#define STR_IDX_	0x00A5	// 'Active'
#define STR_IDX_	0x00A6	// 'Time'
#define STR_IDX_	0x00A7	// 'Please create a new user account.'
#define STR_IDX_	0x00A8	// 'No match found'
#define STR_IDX_	0x00A9	// 'The service line is busy.  Please try again later.'
#define STR_IDX_	0x00AA	// 'Set Time/Date'
#define STR_IDX_	0x00AB	// 'You have no diary today. Do you like to create a new one?'
#define STR_IDX_	0x00AC	// 'Diary Today'
#define STR_IDX_	0x00AD	// '( MM / DD / YYYY )'
#define STR_IDX_	0x00AE	// 'You have no diary today.'
#define STR_IDX_	0x00AF	// 'Time :'
#define STR_IDX_	0x00B0	// 'No data to save !'
#define STR_IDX_	0x00B1	// 'No data to delete !'
#define STR_IDX_	0x00B2	// 'No change, saving !'
#define STR_IDX_	0x00B3	// 'No record in Address Book !'
#define STR_IDX_	0x00B4	// 'No record in this Group !'
#define STR_IDX_	0x00B5	// 'Please input a group name.'
#define STR_IDX_	0x00B6	// 'Message has reached maximum allowed size. Send or save e-mail now.'
#define STR_IDX_	0x00B7	// 'The settings of the active user can't be changed !'
#define STR_IDX_	0x00B8	// 'Must input user name !'
#define STR_IDX_	0x00B9	// 'A Group can not be added$to other Group addresses.'
#define STR_IDX_	0x00BA	// 'No sent mail !'
#define STR_IDX_	0x00BB	// 'There is a problem printing. Check printer cable and power connection, and try again.'
#define STR_IDX_	0x00BC	// 'by Receiver'
#define STR_IDX_	0x00BD	// 'Invalid time !'
#define STR_IDX_	0x00BE	// 'Do you want to save the changes ?'
#define STR_IDX_	0x00BF	// 'Can't delete currently operated record !'
#define STR_IDX_	0x00C0	// 'Do you want to save the changes ?'
#define STR_IDX_	0x00C1	// '% free'
#define STR_IDX_	0x00C2	// 'Please enter the user's name .'
#define STR_IDX_	0x00C3	// 'Please enter the E-Mail address.'
#define STR_IDX_	0x00C4	// 'Please enter the ISP account information.'
#define STR_IDX_	0x00C5	// 'Please enter the ISP account Password.'
#define STR_IDX_	0x00C6	// 'Please enter the dial-up number.'
#define STR_IDX_	0x00C7	// 'Please enter the POP3 account.'
#define STR_IDX_	0x00C8	// 'Please enter the E-Mail password.'
#define STR_IDX_	0x00C9	// 'Please enter the POP3 server address.'
#define STR_IDX_	0x00CA	// 'Please enter the SMTP server address.'
#define STR_IDX_	0x00CB	// 'Please enter the DNS address.'
#define STR_IDX_	0x00CC	// 'Group name has been input, $ are you sure to exit?'
#define STR_IDX_	0x00CD	// 'Please select 1 to 8 for the maximum download size setting.'
#define STR_IDX_	0x00CE	// 'Incorrect E-mail address format.$Do you still want to save it?'
#define STR_IDX_	0x00CF	// 'Your account information has been$modified. Do you want to save it?'
#define STR_IDX_	0x00D0	// 'Active account is deleted ! '
#define STR_IDX_	0x00D1	// 'Memory is full. Please delete some messages and  try again.'
#define STR_IDX_	0x00D2	// 'Are you sure you want $ to delete this message ?'
#define STR_IDX_	0x00D3	// 'Please select 1 to 99 minutes for$the Auto Power off setting.'
#define STR_IDX_	0x00D4	// 'Are you sure you want $ to delete this address ?'
#define STR_IDX_	0x00D5	// 'Memory is full ! Do you want to continue sending ?'
#define STR_IDX_	0x00D6	// 'Memory optimization completed.'
#define STR_IDX_	0x00D7	// 'Warning!  You will not be able to send$and receive E-mail through this account,$are you sure you want to delete it?'
#define STR_IDX_	0x00D8	// 'Please select an active user.'
#define STR_IDX_	0x00D9	// 'You can't delete default user !'
#define STR_IDX_	0x00DA	// 'Please complete application before changing your account !'
#define STR_IDX_	0x00DB	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x00DC	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x00DD	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x00DE	// 'Spelling check finished.'
#define STR_IDX_	0x00DF	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x00E0	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x00E1	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x00E2	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x00E3	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x00E4	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x00E5	// 'M+'
#define STR_IDX_	0x00E6	// 'M-'
#define STR_IDX_	0x00E7	// 'MR'
#define STR_IDX_	0x00E8	// 'MC'
#define STR_IDX_	0x00E9	// 'AC'
#define STR_IDX_	0x00EA	// 'Please input a name.'
#define STR_IDX_	0x00EB	// 'Rename'
#define STR_IDX_	0x00EC	// 'A group can contain only 100 entries.'
#define STR_IDX_	0x00ED	// 'ISP Connect Error !'
#define STR_IDX_	0x00EE	// 'Do you want to erase memory ?'
#define STR_IDX_	0x00EF	// 'Improper Name format.  Please$remove "@" from "User Name" field.'
#define STR_IDX_	0x00F0	// 'Dialing...$Downloading$Disconnecting'
#define STR_IDX_	0x00F1	// 'Downloading message'
#define STR_IDX_	0x00F2	// 'Delete All'
#define STR_IDX_	0x00F3	// 'Low'
#define STR_IDX_	0x00F4	// 'High'
#define STR_IDX_	0x00F5	// 'Off'
#define STR_IDX_	0x00F6	// 'Speaker Volume '
#define STR_IDX_	0x00F7	// 'Do you have call waiting ? '
#define STR_IDX_	0x00F8	// 'Battery low !'
#define STR_IDX_	0x00F9	// 'Status'
#define STR_IDX_	0x00FA	// 'Dialing...    '
#define STR_IDX_	0x00FB	// 'Press <Back> key to escape'
#define STR_IDX_	0x00FC	// 'Logging on...'
#define STR_IDX_	0x00FD	// 'Sending... '
#define STR_IDX_	0x00FE	// ' of '
#define STR_IDX_	0x00FF	// 'Checking E-Mail...'
#define STR_IDX_	0x0100	// 'Receiving Message... '
#define STR_IDX_	0x0101	// 'Disconnecting...'
#define STR_IDX_	0x0102	// 'Are you sure you want$to delete the entire list ?'
#define STR_IDX_	0x0103	// 'The service line is busy, please try again.'
#define STR_IDX_	0x0104	// 'E-Mail To'
#define STR_IDX_	0x0105	// 'Fax To'
#define STR_IDX_	0x0106	// 'Invalid E-mail address.  Please$check the "To" field and try again.'
#define STR_IDX_	0x0107	// 'No dial tone.  Please check the phone line connection and try again.'
#define STR_IDX_	0x0108	// 'Add Author'
#define STR_IDX_	0x0109	// 'Can't send E-Mail and fax at the same time.'
#define STR_IDX_	0x010A	// 'The sender is already in $ your address book.'
#define STR_IDX_	0x010B	// 'The sender has been added $ to your address book.'
#define STR_IDX_	0x010C	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x010D	// 'The phone line connection has been interrupted.  Please check and try again.'
#define STR_IDX_	0x010E	// 'Faxing... Please wait.'
#define STR_IDX_	0x010F	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x0110	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x0111	// 'The E-Mail service is busy or unavailable.  Please try again later.'
#define STR_IDX_	0x0112	// '(24 - Hour)'
#define STR_IDX_	0x0113	// 'Received: '
#define STR_IDX_	0x0114	// 'Rejected: '
#define STR_IDX_	0x0115	// 'Reconnecting...'
#define STR_IDX_	0x0116	// 'Full Content'
#define STR_IDX_	0x0117	// 'Full Screen'
#define STR_IDX_	0x0118	// 'There is a problem with the memory. Do you want to fix it?'
#define STR_IDX_	0x0119	// 'Set Time'
#define STR_IDX_	0x011A	// 'Time : '
#define STR_IDX_	0x011B	// 'Home'
#define STR_IDX_	0x011C	// 'Office'
#define STR_IDX_	0x011D	// 'Mobile'
#define STR_IDX_	0x011E	// 'By Contents'
#define STR_IDX_	0x011F	// 'Select type:'
#define STR_IDX_	0x0120	// 'Select'
#define STR_IDX_	0x0121	// 'AM'
#define STR_IDX_	0x0122	// 'PM'
#define STR_IDX_	0x0123	// 'Message has been saved.'
#define STR_IDX_	0x0124	// 'Please connect the AC adapter and try again.'
#define STR_IDX_	0x0125	// 'You do not have enough battery $power for software update.$Please try again with new batteries.'
#define STR_IDX_	0x0126	// 'AM/PM'
#define STR_IDX_	0x0127	// 'Go To Date'
#define STR_IDX_	0x0128	// '(Date Format:MM/DD/YYYY)'
#define STR_IDX_	0x0129	// 'Find:Author'
#define STR_IDX_	0x012A	// 'Find:Date'
#define STR_IDX_	0x012B	// 'Find:Subject'
#define STR_IDX_	0x012C	// 'Find:Content'
#define STR_IDX_	0x012D	// 'Find:Unread'
#define STR_IDX_	0x012E	// 'Find:Receiver'
#define STR_IDX_	0x012F	// 'Batteries are low!  Please replace$batteries or plug in the AC adapter.'
#define STR_IDX_	0x0130	// 'You have reached the maximum$size of a Daily Event.'
#define STR_IDX_	0x0131	// 'Contact has been saved.'
#define STR_IDX_	0x0132	// 'User account has been saved.'
#define STR_IDX_	0x0133	// 'Daily event has been saved.'
#define STR_IDX_	0x0134	// 'Send Mail'
#define STR_IDX_	0x0135	// 'User has been deleted.'
#define STR_IDX_	0x0136	// 'Check the whole text'
#define STR_IDX_	0x0137	// 'Check from the cursor'
#define STR_IDX_	0x0138	// 'Start Time:'
#define STR_IDX_	0x0139	// 'End    Time:'
#define STR_IDX_	0x013A	// 'Connecting to mail server...'
#define STR_IDX_	0x013B	// 'The service line is busy.  Please try again later.'
#define STR_IDX_	0x013C	// 'Please enter one fax number only.'
#define STR_IDX_	0x013D	// 'Reset System Data'
#define STR_IDX_	0x013E	// 'Clear E-Mail Data'
#define STR_IDX_	0x013F	// 'Clear Address Book Data'
#define STR_IDX_	0x0140	// 'Clear Daily Events Data'
#define STR_IDX_	0x0141	// 'Clear All Data'
#define STR_IDX_	0x0142	// 'No Clear'
#define STR_IDX_	0x0143	// 'Memory is full! $Some mails are not sent out.$please delete some messages  and try again.'
#define STR_IDX_	0x0144	// 'Saving...'
#define STR_IDX_	0x0145	// 'Delete daily events before :'
#define STR_IDX_	0x0146	// 'Are you sure you want to $ delete these daily events ?'
#define STR_IDX_	0x0147	// 'The battery power is running low, the system will power off automatically.'
#define STR_IDX_	0x0148	// 'Settings have been saved.'
#define STR_IDX_	0x0149	// 'Enter the User Name and desired E-Mail Address below for a '
#define STR_IDX_	0x014A	// 'new account. Press the "Request" key below to submit your '
#define STR_IDX_	0x014B	// 'request. E-Mail notification will be sent when your account has '
#define STR_IDX_	0x014C	// 'been approved. '
#define STR_IDX_	0x014D	// 'The fax has been successfully sent.'
#define STR_IDX_	0x014E	// 'Your Address Book can only$store up to 1000 entries.'
#define STR_IDX_	0x014F	// 'Memory is full.$Please go to Settings$to optimize it.'
#define STR_IDX_	0x0150	// 'Duplicated Name in the address book.  Please change the name and try again.'
#define STR_IDX_	0x0151	// 'Are you sure you want to $ delete this event ?'
#define STR_IDX_	0x0152	// '0'
#define STR_IDX_	0x0153	// '4'
#define STR_IDX_	0x0154	// '8'
#define STR_IDX_	0x0155	// '12'
#define STR_IDX_	0x0156	// '24'
#define STR_IDX_	0x0157	// 'every'
#define STR_IDX_	0x0158	// 'hours'
#define STR_IDX_	0x0159	// 'Request'
#define STR_IDX_	0x015A	// 'New mail has been saved.'
#define STR_IDX_	0x015B	// 'You may also call 1-800-GET-MAIL to speak with an operator.'
#define STR_IDX_	0x015C	// '(Additional charges may apply).'
#define STR_IDX_	0x015D	// 'Deleting Application...'
#define STR_IDX_	0x015E	// 'Saving information...'
#define STR_IDX_	0x015F	// 'Are you sure you want to$delete this application?'
#define STR_IDX_	0x0160	// 'The memory for downloading application is full.$Please delete some application.'
#define STR_IDX_	0x0161	// 'Ignore dial tone when dialing ? '
#define STR_IDX_	0x0162	// '&List Format'
#define STR_IDX_	0x0163	// '&Complete Format'
#define STR_IDX_	0x0164	// 'How do you want to $ print the entire addresses ?'
#define STR_IDX_	0x0165	// 'Dial'
#define STR_IDX_	0x0166	// 'Number'
#define STR_IDX_	0x0167	// 'Which field do you want$ to copy to ?'
#define STR_IDX_	0x0168	// 'This caller is already in address book!  Do you want to overwrite it?'
#define STR_IDX_	0x0169	// 'Are you sure you want $ to delete this call ?'
#define STR_IDX_	0x016A	// 'Calling message'
#define STR_IDX_	0x016B	// 'Incoming Call'
#define STR_IDX_	0x016C	// ' / '
#define STR_IDX_	0x016D	// 'How to save new calls ? '
#define STR_IDX_	0x016E	// 'All'
#define STR_IDX_	0x016F	// 'Unanswered'
#define STR_IDX_	0x0170	// 'Fail to receive CID!'
#define STR_IDX_	0x0171	// 'Name:'
#define STR_IDX_	0x0172	// 'Number:'
#define STR_IDX_	0x0173	// 'Date:'
#define STR_IDX_	0x0174	// 'Time:'
#define STR_IDX_	0x0175	// '&Home'
#define STR_IDX_	0x0176	// '&Office'
#define STR_IDX_	0x0177	// '&Mobile'
#define STR_IDX_	0x0178	// 'Connection is OK! $Your phone can work now!'
#define STR_IDX_	0x0179	// 'Answered'
#define STR_IDX_	0x017A	// 'Checking...$Press <Back> key to escape'
#define STR_IDX_	0x017B	// 'Unable to copy.  Please remove the non-numeric characters.'
#define STR_IDX_	0x017C	// 'Press any key to escape'
#define STR_IDX_	0x017D	// '(LD)'
#define STR_IDX_	0x017E	// 'This call hasn't existed.'
#define STR_IDX_	0x017F	// 'Send'
#define STR_IDX_	0x0180	// 'Reply-To: '
#define STR_IDX_	0x0181	// 'Swap First/Last'
#define STR_IDX_	0x0182	// 'The form can't be edited while in the "Outbox".'
#define STR_IDX_	0x0183	// 'There may have some mistakes in this form.$And it can't be opened.'
#define STR_IDX_	0x0184	// 'To activate a new E-Mail account, please call:'
#define STR_IDX_	0x0185	// '1-888-403-7050'
#define STR_IDX_	0x0186	// 'A representative will assist you with your request.'
#define STR_IDX_	0x0187	// 'Restore Default Account'
#define STR_IDX_	0x0188	// 'Update'
#define STR_IDX_	0x0189	// 'This is for demonstration$purposes only. This content$can not be removed.'
#define STR_IDX_	0x018A	// 'Demonstration only'
#define STR_IDX_	0x018B	// 'This is for demonstration$purposes only. This content$can not be modified.'
#define STR_IDX_	0x018C	// 'All Mail Sent.'
#define STR_IDX_	0x018D	// 'Mail Sent.'
#define STR_IDX_	0x018E	// 'Messages Sent.'
#define STR_IDX_	0x018F	// 'No New Mail.'
#define STR_IDX_	0x0190	// 'New E-mails: '
#define STR_IDX_	0x0191	// 'New Yahoo! Information: '
#define STR_IDX_	0x0192	// 'Saving Yahoo! information...'
#define STR_IDX_	0x0193	// 'Automatically Check Mail'
#define STR_IDX_	0x0194	// 'Auto Check Time 1'
#define STR_IDX_	0x0195	// 'Time 2'
#define STR_IDX_	0x0196	// 'Battery Status: '
#define STR_IDX_	0x0197	// 'Current Time: '
#define STR_IDX_	0x019A	// ''
#define STR_IDX_	0x019B	// 'Details'
#define STR_IDX_	0x019C	// 'The memory is less than 40%, do you want to continue?'
#define STR_IDX_	0x019D	// 'Speaker '
#define STR_IDX_	0x019E	// 'Set Time/Date'
#define STR_IDX_	0x019F	// 'Invalid E-mail Address.$ Please check the "To" field and try again.'
#define STR_IDX_	0x01A0	// 'New MyCIDCO Infomation:'
#define STR_IDX_	0x01A1	// 'Saving MyCIDCO infomation...'
#define STR_IDX_	0x01A2	// 'Memory is nearly full,$ please delete some messages $and try again.'
#define STR_IDX_	0x01A3	// 'Are you sure to clear?'
#define STR_IDX_	0x01A4	// ''
#endif
